name: web_crawling_data_into_firebase

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'

jobs:
  my-first-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3 
    - name: generate keys
      run: |
        echo -n '${{ secrets.FIREBASE3_KEY }}' > firebase_key.json
        echo -n '${{ secrets.API_KEY }}' > apikey.txt
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: installing requirements
      run: |
        pip install -r requirements.txt
    - name: running main file
      run: |
        python3 main.py
